#!/usr/bin/env python3
"""Render a color-coded visual difference between two STL meshes with OpenSCAD."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


CAMERAS = {
    "iso": "0,0,0,55,0,25,0",
    "top": "0,0,0,0,0,0,0",
    "front": "0,0,0,90,0,0,0",
    "right": "0,0,0,90,0,90,0",
}


def parse_imgsize(value: str) -> str:
    match = re.fullmatch(r"([1-9][0-9]*)[x,]([1-9][0-9]*)", value)
    if not match:
        raise argparse.ArgumentTypeError("use WIDTHxHEIGHT, for example 1200x900")
    return f"{match.group(1)},{match.group(2)}"


def scad_string(path: Path) -> str:
    """Quote a path as a string accepted by OpenSCAD."""
    return json.dumps(str(path), ensure_ascii=False)


def build_scene(before: Path, after: Path, show_common: bool) -> str:
    common = """
color([0.72, 0.72, 0.72, 0.20])
intersection() {
    before_model();
    after_model();
}
""" if show_common else ""
    return f"""// Generated by stl_diff.py. Red = added, blue = removed, gray = unchanged.
module before_model() {{ import({scad_string(before)}, convexity=10); }}
module after_model() {{ import({scad_string(after)}, convexity=10); }}
{common}
color([0.10, 0.38, 1.00, 1.00])
difference() {{
    before_model();
    after_model();
}}

color([1.00, 0.16, 0.06, 1.00])
difference() {{
    after_model();
    before_model();
}}
"""


def existing_stl(value: str) -> Path:
    path = Path(value).expanduser().resolve()
    if not path.is_file():
        raise argparse.ArgumentTypeError(f"STL file does not exist: {path}")
    if path.suffix.lower() != ".stl":
        raise argparse.ArgumentTypeError(f"expected an .stl file: {path}")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Render an STL revision diff. Red is added material, blue is removed "
            "material, and translucent gray is unchanged volume."
        )
    )
    parser.add_argument("before", type=existing_stl, help="older STL in the shared coordinate frame")
    parser.add_argument("after", type=existing_stl, help="newer STL in the shared coordinate frame")
    parser.add_argument("-o", "--output", type=Path, required=True, help="output PNG path")
    parser.add_argument("--view", choices=CAMERAS, default="iso", help="orthographic camera view")
    parser.add_argument("--imgsize", type=parse_imgsize, default="1200,900", help="WIDTHxHEIGHT")
    parser.add_argument("--colorscheme", default="Cornfield", help="OpenSCAD color scheme")
    parser.add_argument("--openscad", default="openscad", help="OpenSCAD executable")
    parser.add_argument("--diff-only", action="store_true", help="hide unchanged gray volume")
    parser.add_argument("--force", action="store_true", help="replace an existing output PNG")
    parser.add_argument("--keep-scad", type=Path, help="also save the generated comparison SCAD")
    args = parser.parse_args()

    executable = shutil.which(args.openscad)
    if executable is None:
        parser.error(f"OpenSCAD executable not found: {args.openscad}")

    output = args.output.expanduser().resolve()
    if output.suffix.lower() != ".png":
        parser.error("output must use the .png extension")
    if output in {args.before, args.after}:
        parser.error("output must not overwrite an input STL")
    if output.exists() and not args.force:
        parser.error(f"output already exists (use --force to replace it): {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.unlink(missing_ok=True)

    scene = build_scene(args.before, args.after, show_common=not args.diff_only)
    if args.keep_scad:
        kept = args.keep_scad.expanduser().resolve()
        kept.parent.mkdir(parents=True, exist_ok=True)
        kept.write_text(scene, encoding="utf-8")

    with tempfile.TemporaryDirectory(prefix="openscad-stl-diff-") as temp_dir:
        scene_path = Path(temp_dir) / "diff.scad"
        scene_path.write_text(scene, encoding="utf-8")
        command = [
            executable,
            "-o", str(output),
            "--render",
            "--autocenter",
            "--viewall",
            f"--imgsize={args.imgsize}",
            f"--camera={CAMERAS[args.view]}",
            "--projection=ortho",
            f"--colorscheme={args.colorscheme}",
            str(scene_path),
        ]
        completed = subprocess.run(command, text=True, capture_output=True, check=False)

    log = completed.stdout + completed.stderr
    if completed.returncode != 0 or "ERROR:" in log:
        sys.stderr.write(completed.stdout)
        sys.stderr.write(completed.stderr)
        output.unlink(missing_ok=True)
        return completed.returncode or 1
    signature = b""
    if output.is_file():
        with output.open("rb") as png_file:
            signature = png_file.read(8)
    if signature != b"\x89PNG\r\n\x1a\n":
        sys.stderr.write("OpenSCAD completed but did not create a valid PNG.\n")
        return 1

    print(f"Wrote {output}")
    print("Legend: red = added, blue = removed, translucent gray = unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
